package easy;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/*
 *  Players generally sit in a circle. The player designated to go first says the number "1", and each player thenceforth counts one number in turn. However, any number divisible by 'A' e.g. three is replaced by the word fizz and any divisible by 'B' e.g. five by the word buzz. Numbers divisible by both become fizz buzz. A player who hesitates or makes a mistake is either eliminated.

Write a program that prints out the the pattern generated by such a scenario given the values of 'A'/'B' and 'N' which are read from an input text file. The input text file contains three space delimited numbers i.e. A, B, N. The program should then print out the final series of numbers using 'F' for fizz, 'B' for 'buzz' and 'FB' for fizz buzz.
Input sample:

Your program should read an input file (provided on the command line) which contains multiple newline separated lines. Each line will contain 3 numbers which are space delimited. The first number is first number to divide by ('A' in this example), the second number is the second number to divide by ('B' in this example) and the third number is where you should count till ('N' in this example). You may assume that the input file is formatted correctly and is the numbers are valid positive integers. E.g.
Output sample:

Print out the series 1 through N replacing numbers divisible by 'A' by F, numbers divisible by 'B' by B and numbers divisible by both as 'FB'. Since the input file contains multiple sets of values, your output will print out one line per set. Ensure that there are no trailing empty spaces on each line you print. E.g.

Constraints:
The number of test cases <= 20
"A" is in range [1, 20]
"B" is in range [1, 20]
"N" is in range [21, 100] 
 */


public class FizzBuzz {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		BufferedReader br = null;

		try {

			String sCurrentLine;

			StringBuffer result = null;

			int A = 0,B = 0, N = 0;


			String[] spaceSeparatedArray = null;

			br = new BufferedReader(new FileReader(args[0]));

			while ((sCurrentLine = br.readLine()) != null) {

				spaceSeparatedArray = sCurrentLine.split(" ");

				
				A = Integer.parseInt(spaceSeparatedArray[0]);
				B = Integer.parseInt(spaceSeparatedArray[1]);
				N = Integer.parseInt(spaceSeparatedArray[2]);
				
				result = new StringBuffer();		

				for(int i=1;i<=N;i++)	
				{

					if(i%A==0 && i%B==0)
						result.append("FB");
					else if(i%A==0)
						result.append("F");
					else if(i%B==0)
						result.append("B");
					else
						result.append(i+"");

					result.append(" ");

				}



				String mynewstring = result.toString();

				System.out.println(mynewstring.trim());
			}

		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (br != null)br.close();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
		}

	}

}
